language: csharp
solution: ./kvadratnoye_lab2_tp/kvadratnoye_lab2_tp.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore ./kvadratnoye_lab2_tp/kvadratnoye_lab2_tp.sln
script:
  - xbuild /p:Configuration=Release kvadratnoye_lab2_tp.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./kvadratnoye_lab2_tp/UnitTest_lab_2/bin/Debug/UnitTest_lab_2.dll